Instrucciones para añadir iconos en las capas del árbol
SNMBArgentina/doc-snmb pull request #5
Opened 2020-03-05 09:15 UTC by PeteRey

2020-03-05 09:43 UTC, mpericay requested changes

2020-03-05 09:43 UTC, mpericay commented on docs/user/add_icons.md
> +En `info File` se define el nombre del fichero HTML que contiene la información de la capa. Este fichero HTML se localiza en la ruta `static/loc/{lang}/html`, siendo `{lang}` el idioma utilizado, por
'info File' o 'infoFile'?

2020-03-05 09:43 UTC, mpericay commented on docs/user/add_icons.md
> +En `info Link` se define la ruta completa (URL) al fichero HTML. Por ejemplo, para el idioma español habría que poner `static/loc/es/html/fichero.html`.
'infoLink'

2020-03-05 09:45 UTC, PeteRey commented on docs/user/add_icons.md
> +En `info File` se define el nombre del fichero HTML que contiene la información de la capa. Este fichero HTML se localiza en la ruta `static/loc/{lang}/html`, siendo `{lang}` el idioma utilizado, por
Lo puse tal y como sale en el editor.

2020-03-05 09:47 UTC, mpericay approved these changes
Ok, entonces está bien, disculpas! Pensaba en layers.json ...

2020-03-12 17:37 UTC, michogar approved these changes

2020-03-12 17:37 UTC, merged